### ISSUE TITLE
Build for production fails with vite and vue 3

### ISSUE THREAD

**Issue by bereydev** [epicmaxco/vuestic-ui#1511]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
Clone this repo : [bereydev/wizy-front](https://github.com/bereydev/wizy-front)
`pnpm build`

**What is the expected behavior?**
The project should build correctly without errors

**What is the current behavior?**
The following logs are output:
```
vite v2.8.3 building SSR bundle for production...
@vueform/multiselect doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
✓ 114 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38 KiB
.vite-ssg-temp/main.mjs                    231.14 KiB
.vite-ssg-temp/assets/style.7f1dd47d.css   112.40 KiB

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/Users/jon/prog/wizy-front/node_modules/.pnpm/vuestic-ui@1.3.4_vue@3.2.31/node_modules/vuestic-ui/dist/cjs/main.js:1
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("lodash-es"),t=require("vue"),n=require("tslib"),a=require("colortranslator"),r=require("@vue/server-renderer"),o=require("asva-executors"),i=require("@popperjs/core"),s=require("cleave.js"),l=require("detect-browser"),d=require("element-resize-detector");function _interopDefaultLegacy(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var c=_interopDefaultLegacy(s),p=_interopDefaultLegacy(d);function styleInject(e,t){void 0===t&&(t={});var n=t.insertAt;if(e&&"undefined"!=typeof document){var a=document.head||document.getElementsByTagName("head")[0],r=document.createElement("style");r.type="text/css","top"===n&&a.firstChild?a.insertBefore(r,a.firstChild):a.appendChild(r),r.styleSheet?r.styleSheet.cssText=e:r.appendChild(document.createTextNode(e))}}const v="undefined"==typeof window;let u,m=!1;function getPlatform(e){const t=function getMatch(e,t){const n=/(edge)\/([\w.]+)/.exec(e)||/(opr)[\/]([\w.]+)/.exec(e)||/(vivaldi)[\/]([\w.]+)/.exec(e)||/(chrome)[\/]([\w.]+)/.exec(e)||/(iemobile)[\/]([\w.]+)/.exec(e)||/(version)(applewebkit)[\/]([\w.]+).*(safari)[\/]([\w.]+)/.exec(e)||/(webkit)[\/]([\w.]+).*(version)[\/]([\w.]+).*(safari)[\/]([\w.]+)/.exec(e)||/(webkit)[\/]([\w.]+)/.exec(e)||/(opera)(?:.*version|)[\/]([\w.]+)/.exec(e)||/(msie) ([\w.]+)/.exec(e)||e.indexOf("trident")>=0&&/(rv)(?::| )([\w.]+)/.exec(e)||e.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(e)||[];return{browser:n[5]||n[3]||n[1]||"",version:n[2]||n[4]||"0",versionNumber:n[4]||n[2]||"0",platform:t[0]||""}}(e=(e||navigator.userAgent||navigator.vendor||window.opera).toLowerCase(),function getPlatformMatch(e){return/(ipad)/.exec(e)||/(ipod)/.exec(e)||/(windows phone)/.exec(e)||/(iphone)/.exec(e)||/(kindle)/.exec(e)||/(silk)/.exec(e)||/(android)/.exec(e)||/(win)/.exec(e)||/(mac)/.exec(e)||/(linux)/.exec(e)||/(cros)/.exec(e)||/(playbook)/.exec(e)||/(bb)/.exec(e)||/(blackberry)/.exec(e)||[]}(e)),n={};return t.browser&&(n[t.browser]=!0,n.version=t.version,n.versionNumber=parseInt(t.versionNumber,10)),t.platform&&(n[t.platform]=!0),(n.android||n.bb||n.blackberry||n.ipad||n.iphone||n.ipod||n.kindle||n.playbook||n.silk||n["windows phone"])&&(n.mobile=!0),(n.ipod||n.ipad||n.iphone)&&(n.ios=!0),n["windows phone"]&&(n.winphone=!0,delete n["windows phone"]),(n.cros||n.mac||n.linux||n.win)&&(n.desktop=!0),(n.chrome||n.opr||n.safari||n.vivaldi)&&(n.webkit=!0),(n.rv||n.iemobile)&&(t.browser="ie",n.ie=!0),n.edge&&(t.browser="edge",n.edge=!0),(n.safari&&n.blackberry||n.bb)&&(t.browser="blackberry",n.blackberry=!0),n.safari&&n.playbook&&(t.browser="playbook",n.playbook=!0),n.opr&&(t.browser="opera",n.opera=!0),n.safari&&n.android&&(t.browser="android",n.android=!0),n.safari&&n.kindle&&(t.browser="kindle",n.kindle=!0),n.safari&&n.silk&&(t.browser="silk",n.silk=!0),n.vivaldi&&(t.browser="vivaldi",n.vivaldi=!0),n.name=t.browser,n.platform=t.platform,v||(window.process&&window.process.versions&&window.process.versions.electron?n.electron=!0:0===document.location.href.indexOf("chrome-extension://")?n.chromeExt=!0:(window._cordovaNative||window.cordova)&&(n.cordova=!0),m=void 0===n.cordova&&void 0===n.electron&&!!document.querySelector("[data-server-rendered]")),n}function hasWebStorage(){if(void 0!==u)return u;try{if(window.localStorage)return u=!0,!0}catch(e){}return u=!1,!1}function getClientProperties(){return{has:{touch:!!("ontouchstart"in document.documentElement)||window.navigator.msMaxTouchPoints>0,webStorage:hasWebStorage()},within:{iframe:window.self!==window.top}}}var h={has:{touch:!1,webStorage:!1},parseSSR(e){return e?{is:getPlatform(e.req.headers["user-agent"]),has:this.has,within:this.within}:{is:getPlatform(),...getClientProperties()}},install(e,t,n){v?t.server.push(((e,t)=>{e.platform=this.parseSSR(t.ssr)})):(this.is=getPlatform(),m?(t.takeover.push((e=>{m=!1,Object.assign(e.platform,getClientProperties())})),n.util.defineReactive(e,"platform",this)):(Object.assign(this,getClientProperties()),e.platform=this))}};var f={install(e){e.config.globalProperties.$closeDropdown=function(){let e=this;for(;e=e.$parent;){if("VaDropdown"===e.$options.name){e.hide();break}}}}};const g=Symbol("LocalConfigKey"),b=t.computed((()=>[]));function useLocalConfig(){return t.inject(g,b)}var y=t.defineComponent({name:"VaConfig",props:{components:{type:Object,default:()=>({})}},setup(e){const{components:n}=t.toRefs(e),a=useLocalConfig(),r=t.computed((()=>[...a.value,n.value]));return t.provide(g,r),{}},render(){return this.$slots.default?this.$slots.default():null}});const x=[{name:"{icon}",class:"material-icons",resolve:({icon:e})=>({content:e})}],_=[{name:"arrow_back_ios",to:"arrow_back_ios"},{name:"arrow_forward_ios",to:"arrow_forward_ios"},{name:"first_page",to:"first_page"},{name:"last_page",to:"last_page"},{name:"chevron_right",to:"chevron_right"},{name:"chevron_left",to:"chevron_left"},{name:"expand_more",to:"expand_more"},{name:"expand_less",to:"expand_less"},{name:"arrow_drop_down",to:"arrow_drop_down"},{name:"arrow_drop_up",to:"arrow_drop_up"},{name:"calendar_today",to:"calendar_today"},{name:"delete_outline",to:"delete_outline"},{name:"clear",to:"clear"},{name:"check",to:"check"},{name:"warning",to:"warning"},{name:"highlight_off",to:"highlight_off"},{name:"close",to:"close"},{name:"done",to:"done"},{name:"cancel",to:"cancel"},{name:"loop",to:"loop"}],createIconsConfig=e=>(e.aliases=e.aliases||[],e.fonts=e.fonts||[],[...e.aliases,..._,...e.fonts,...x]),w=t.ref({colors:{primary:"#2C82E0",secondary:"#767C88",background:"#f4f8fa",success:"#40e583",info:"#2c82e0",danger:"#DE1041",warning:"#FFAC0A",gray:"#babfc2",dark:"#1B1A1F",divider:"#E1E9F8"},icons:createIconsConfig({}),components:{VaIcon:{sizesConfig:{defaultSize:24,sizes:{small:16,medium:24,large:32}}},VaRating:{sizesConfig:{defaultSize:24,sizes:{small:16,medium:24,large:32}}}},componentsAll:{}});function setGlobalConfig(t){const n="function"==typeof t?t(w.value):t;w.value=e.cloneDeep(n)}function mergeGlobalConfig(t){const n="function"==typeof t?t(w.value):t;w.value=e.merge(e.cloneDeep(w.value),n)}function getGlobalConfig(){return w.value}function useGlobalConfig(){return{setGlobalConfig:setGlobalConfig,getGlobalConfig:getGlobalConfig,mergeGlobalConfig:mergeGlobalConfig,globalConfig:w}}function normalizeProps$1(t){switch(!0){case e.isArray(t):return t.reduce(((e,t)=>({...e,[t]:null})),{});case e.isObject(t):return t;default:return{}}}function mergeProps$1(e,t,n="props"){const{mixins:a,extends:r}=t;r&&mergeProps$1(e,r,n),a&&a.forEach((t=>mergeProps$1(e,t,n)));const o=normalizeProps$1(t[n]);for(const t in o)e[t]=o[t]}function resolveProps$1(e,t="props"){var n,a;const r=null!==(n=e.mixins)&&void 0!==n?n:[],o={};mergeProps$1(o,null!==(a=e.extends)&&void 0!==a?a:[],t);for(let e=0;e<r.length;e++)mergeProps$1(o,r[e],t);return Object.assign(o,normalizeProps$1(e[t])),o}const formatEmitString=t=>{const[n,a]=t.split(":");return a?[e.upperFirst(n),e.camelCase(a)].join(":"):e.upperFirst(e.camelCase(n))},withConfigTransport=n=>{const a=function getComponentOptions$1(e){switch(!0){case Boolean(e.options):return e.options;case Boolean(e.__vccOpts)||Boolean(e.__b):return{...e.__b,...e.__vccOpts};default:return e}}(n),r=resolveProps$1(a),o=Object.keys(resolveProps$1(a,"emits")),i={...r},s={...a.methods},l=Object.keys(i),d=n.__vccOpts,c=e.upperFirst(e.camelCase(d?d.name:n.name));return{name:`WithConfigTransport${c||"Component"}`,props:l,emits:o,methods:Object.keys(s).reduce(((e,t)=>({...e,[t]:function(...e){return this.$refs.innerRef[t](...e)}})),{}),setup(e,n){const a=useLocalConfig(),{getGlobalConfig:r}=useGlobalConfig();return{computedProps:t.computed((()=>{var t;const n={...{...r().componentsAll,...null===(t=r().components)||void 0===t?void 0:t[c]},...a.value.reduce(((e,t)=>t[c]?{...e,...t[c]}:e),{})};return Object.entries(i).reduce(((t,[a,r])=>(t[a]=((t,a)=>void 0!==e[t]?e[t]:void 0!==n[t]?n[t]:"function"==typeof a?a():a)(a,r.default),t)),{})})),proxiedEmits:o.reduce(((e,t)=>({...e,[`on${formatEmitString(t)}`]:(...e)=>n.emit(t,...e)})),{})}},render(){return t.h(n,{...this.computedProps,...this.proxiedEmits,ref:"innerRef"},{...this.$slots})}}};
                                                                          ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jon/prog/wizy-front/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/lodash.js from /Users/jon/prog/wizy-front/node_modules/.pnpm/vuestic-ui@1.3.4_vue@3.2.31/node_modules/vuestic-ui/dist/cjs/main.js not supported.
Instead change the require of lodash.js in /Users/jon/prog/wizy-front/node_modules/.pnpm/vuestic-ui@1.3.4_vue@3.2.31/node_modules/vuestic-ui/dist/cjs/main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/jon/prog/wizy-front/node_modules/.pnpm/vuestic-ui@1.3.4_vue@3.2.31/node_modules/vuestic-ui/dist/cjs/main.js:1:75)
    at async Promise.all (index 0)
    at async build (/Users/jon/prog/wizy-front/node_modules/.pnpm/vite-ssg@0.17.10_1d9d03efcb68c10fe000b6b7ca1deeb9/node_modules/vite-ssg/dist/node/cli.cjs:180:87)
    at async Object.handler (/Users/jon/prog/wizy-front/node_modules/.pnpm/vite-ssg@0.17.10_1d9d03efcb68c10fe000b6b7ca1deeb9/node_modules/vite-ssg/dist/node/cli.cjs:314:3) {
  code: 'ERR_REQUIRE_ESM'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Other information**
The project run perfectly fine in development I just would like to be able to use Vuestic's awesome components in production

**Comment by bereydev** [comment]
We currently push the project on Netlify with automatic build can you please explain me how to make an alias ? I'm not really at ease with bundlers and modules. We plan to release a version of our app using Vuestic before the end of the month so I don't know if the next release will be out. 😇

> Hi. You can use temporary use `dist/esm-ssr` build instead of cjs, Simply make an alias. I made a PR that should fix your issue. Should be merged until next release.
