### ISSUE TITLE
mergeGlobalConfig/setGlobalConfig doesn't work in Composition API templates

### ISSUE THREAD

**Issue by damonto** [epicmaxco/vuestic-ui#3020]
**Vuestic-ui version:** 1.6.0

**Steps to reproduce**
I want to switch to dark theme automatically based on system preferences, but the mergeGlobalConfig/setGlobalConfig function doesn't work

```vue
<template lang="pug">
router-view
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue'
import { useGlobalConfig } from 'vuestic-ui'
const isDarkMode = ref(
  <boolean>Boolean(window?.matchMedia('(prefers-color-scheme: dark)')?.matches)
)
if (typeof window?.matchMedia !== 'undefined') {
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (e) => {
    isDarkMode.value = Boolean(e.matches)
  })
}

const setApplicationUIMode = (isDarkMode: boolean) => {
  useGlobalConfig().mergeGlobalConfig({
    colors: {
      currentPresetName: isDarkMode ? 'dark' : 'light'
    }
  })
}

setApplicationUIMode(isDarkMode.value)
watch(isDarkMode, (value: boolean) => {
  setApplicationUIMode(value)
})
</script>
```

Error:
```
global-config.ts:46 Uncaught (in promise) Error: Vue app not found for provide
    at provideForCurrentApp (global-config.ts:46:9)
    at useGlobalConfig (global-config.ts:59:3)
    at setApplicationUIMode (App.vue:18:3)
    at App.vue:27:3
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at job (runtime-core.esm-bundler.js:1812:17)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:36)
    at flushJobs (runtime-core.esm-bundler.js:406:17)
```

Can you provide an option to automatically switch themes based on system preferences?

**Comment by damonto** [comment]
solved:
```vue
import { useColors } from 'vuestic-ui'
const colors = useColors()
colors.applyPreset(
  Boolean(window?.matchMedia('(prefers-color-scheme: dark)')?.matches) ? 'dark' : 'light'
)
if (typeof window?.matchMedia !== 'undefined') {
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (e) => {
    colors.applyPreset(Boolean(e.matches) ? 'dark' : 'light')
  })
}
```
