### ISSUE TITLE
Error requiring module in vuestic-ui when running yarn serve:docs

### ISSUE THREAD

**Issue by Skander999** [epicmaxco/vuestic-ui#3422]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce:**
1. Clone the Vuestic-ui repository
2. Run `yarn install`
3. Run `yarn serve:docs`

**What is the expected behavior?**
The Vuestic-ui documentation website should start and be visible in the browser.

**What is the current behavior?**
I get the following error:
` ERROR  Error while requiring module ./modules/page-config: Error: Cannot find module 'C:\New\vuestic-ui\node_modules\vuestic-ui\dist\cjs\main.js'           19:36:05

 ERROR  Cannot start nuxt:  Cannot find module 'C:\New\vuestic-ui\node_modules\vuestic-ui\dist\cjs\main.js'                                                  19:36:05

  at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
  at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
  at resolveExports (node:internal/modules/cjs/loader:482:14)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (C:\New\vuestic-ui\node_modules\jiti\dist\jiti.js:1:241025)
  at jiti (C:\New\vuestic-ui\node_modules\jiti\dist\jiti.js:1:243309)
  at modules\page-config\blocks\api\component-parser\index.ts:3:42
  at jiti (C:\New\vuestic-ui\node_modules\jiti\dist\jiti.js:1:245784)                                                                                        19:36:03  

`
**Other information:**
I've already tried deleting the `node_modules` directory and running `yarn install` again, but the error persists.

**Comment by m0ksem** [comment]
Hi @Skander999, can you try now? Notice we now require node 18 in .nvmrc. All dependecies should be synced now. If this doesnt work, try to run `yarn build` in root workspace.

**Comment by Skander999** [comment]
Thank you it works after running yarn build!

**Comment by m0ksem** [comment]
closed in https://github.com/epicmaxco/vuestic-ui/pull/3475
