### ISSUE TITLE
props.items.map is not a function

### ISSUE THREAD

**Issue by WangCEChen** [epicmaxco/vuestic-ui#3483]
**Vuestic-ui version:** 1.6.5

**Steps to reproduce**
dont know how reproduce, cause some pages issued, some pages look fine
**What is the expected behavior?**

**What is the current behavior?**
![image](https://github.com/epicmaxco/vuestic-ui/assets/28552100/4e0616ae-d5b3-4300-a4e7-ff3f3288b34a)

**Other information**
ERROR
props.items.map is not a function
TypeError: props.items.map is not a function
    at ReactiveEffect.eval [as fn] (webpack-internal:///./node_modules/vuestic-ui/dist/es/src/components/va-data-table/hooks/useRows-4dd6ceac.mjs:42:88)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)
    at get value [as value] (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:1112:33)
    at ReactiveEffect.eval [as fn] (webpack-internal:///./node_modules/vuestic-ui/dist/es/src/components/va-data-table/hooks/useFilterable-334f2b56.mjs:22:18)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)
    at get value [as value] (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:1112:33)
    at ReactiveEffect.getter [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1576:27)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)
    at job (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1644:31)
    at flushPreFlushCbs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:418:7)

**Comment by m0ksem** [comment]
Looks like you're passing something different from `array` or `undefined` to data table items. Don't you see any warning from vue like `Expected array, but got something else`.

**Comment by m0ksem** [comment]
This is looks good for me. I assume issue caused because there was wrong prop passed to VaDataTable and vue should throw a warn about it. Feel free to reopen this issue and provide better info about this issue if I'm wrong.
