### ISSUE TITLE
Cannot use Toast.init outside of a vue component since v1.6.5

### ISSUE THREAD

**Issue by deepakduggirala** [epicmaxco/vuestic-ui#3494]
**Vuestic-ui version:** 1.6.6

**Steps to reproduce**
Create a toast.service.js to overload the init function with custom position and color to make it easier to call from the application code.

services/toast.js
```javascript
import { useToast } from "vuestic-ui";
const { init, close, closeAll } = useToast();

class Toast {
  success(message) {
    init({
      message,
      position: "bottom-right",
      color: "success",
    });
  }
  error(message) {
    init({
      message,
      position: "bottom-right",
      color: "danger",
    });
  }
  info(message) {
    init({
      message,
      position: "bottom-right",
      color: "primary",
    });
  }
}

export default new Toast();
```

Vue Component:
```html
<script setup>
import toast from "@/services/toast";

apiService
  .getAll()
  .catch((err) => {
    if (err?.response?.status == 404) 
      toast.error("Could not find the active workflows");
   }
</script>
```

**What is the expected behavior?**
Should show the toast

**What is the current behavior?**
Does not show the toast becase of this error
Stacktrace:
```
useCache.ts:8 Uncaught (in promise) Error: Vuestic cache plugin is not registered!
    at useCache (useCache.ts:8:11)
    at useColors (useColors.ts:124:17)
    at Object.setup (VaToast.vue:89:26)
    at customSetup (createProxyComponent.ts:78:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
```

**Other information**
Toast.init uses useColor which uses useCache. But since v1.6.5, useCache constructor (packages/ui/src/composables/useCache.ts) requires `inject` which will not work outside a setup function of a vue component. 

Change leading to the bug: https://github.com/epicmaxco/vuestic-ui/commit/d6fbc38595f510a2331fb6e8d10628e0fb90402c#diff-236d8ada5b7af89f5eed69403dceb919484966b47f448741ef21903fa77d6b76

**Comment by pogrib0k** [comment]
Can I work on this?
